### ISSUE TITLE
bash (command) completion

### ISSUE THREAD

**Issue by booyaa** [intecture/cli#12] opened 2017-05-29 16:00 UTC
I'm lazy, it'd be nice to do

```
icli <tab>
  run project payload host user
incli proj<tab>
incli project <tab>
incli project init foo<tab>
  C PHP
incli project init foo P<tab>
incli project init foo PHP
```

If `incli` gets ported to clap (as per #11 ), you get this stuff for free.

**Comment by itpetey** [comment] 2017-06-06 15:18
I'm going to close this as a duplicate of intecture/cli#11 as porting to Clap is the intention.

**Closed as completed by itpetey** 2017-06-06 15:18 UTC
Labels: duplicate
